/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import bll.Userdatabll;
import dao.UsedataDAOImpl;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;

/**
 *
 * @author thapa
 */
public class CRegisterUser extends javax.swing.JFrame {

    /**
     * Creates new form CRegisterUser
     */
    public CRegisterUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtfistname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtlastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        psdpass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        psdconfpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 90, 40));

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel3.setText("First Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 135, -1));

        txtfistname.setBackground(new java.awt.Color(0, 102, 102));
        txtfistname.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        txtfistname.setForeground(new java.awt.Color(255, 255, 255));
        txtfistname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfistnameActionPerformed(evt);
            }
        });
        jPanel3.add(txtfistname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 300, 36));

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel4.setText("Last Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        txtlastname.setBackground(new java.awt.Color(0, 102, 102));
        txtlastname.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        txtlastname.setForeground(new java.awt.Color(255, 255, 255));
        txtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastnameActionPerformed(evt);
            }
        });
        jPanel3.add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 280, 36));

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel5.setText("Phone No.");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 179, -1));

        txtnum.setBackground(new java.awt.Color(0, 102, 102));
        txtnum.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        txtnum.setForeground(new java.awt.Color(255, 255, 255));
        txtnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumActionPerformed(evt);
            }
        });
        jPanel3.add(txtnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 300, 36));

        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel6.setText("Gmail");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 101, -1));

        txtemail.setBackground(new java.awt.Color(0, 102, 102));
        txtemail.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        txtemail.setForeground(new java.awt.Color(255, 255, 255));
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel3.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 280, 36));

        jLabel7.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel7.setText("Password");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 113, -1));

        psdpass.setBackground(new java.awt.Color(0, 102, 102));
        psdpass.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        psdpass.setForeground(new java.awt.Color(255, 255, 255));
        psdpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psdpassActionPerformed(evt);
            }
        });
        jPanel3.add(psdpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 300, 40));

        jLabel8.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel8.setText("Confirm Password");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 177, -1));

        psdconfpass.setBackground(new java.awt.Color(0, 102, 102));
        psdconfpass.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        psdconfpass.setForeground(new java.awt.Color(255, 255, 255));
        psdconfpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psdconfpassActionPerformed(evt);
            }
        });
        jPanel3.add(psdconfpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 270, 40));

        jButton1.setBackground(new java.awt.Color(153, 0, 204));
        jButton1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        jLabel2.setText("Register Now");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 300, 40));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 700, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 700, 510));

        setSize(new java.awt.Dimension(714, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameActionPerformed

    private void txtfistnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfistnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfistnameActionPerformed

    private void txtnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtemailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Userdatabll data = new Userdatabll();
        String fname = txtfistname.getText();
        String lname = txtlastname.getText();
        String num = txtnum.getText();
        String Email = txtemail.getText();
        String pass = psdpass.getText();
        String confirmpass = psdconfpass.getText();
        data.setEmail(Email);
        data.setFname(fname);
        data.setLname(lname);
        data.setNum(num);
        data.setPass(pass);
        data.setConfirmpass(confirmpass);
        UsedataDAOImpl da = new UsedataDAOImpl();
        if("".equals(lname) || fname.equals("")|| num.equals("")|| Email.equals("")||pass.equals("")||confirmpass.equals("")){
            JOptionPane.showMessageDialog(null,"Fill all the area"); }
        else if(!pass.equals(confirmpass)){
            JOptionPane.showMessageDialog(null,"Passwords does not match");}
        else{
            
            try {
                da.saveuserdata(data);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(CRegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            
        JOptionPane.showMessageDialog(null, "Sucessfully Registered");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UserLogIn uli = new UserLogIn();
        uli.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void psdpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psdpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psdpassActionPerformed

    private void psdconfpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psdconfpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psdconfpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRegisterUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField psdconfpass;
    private javax.swing.JPasswordField psdpass;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfistname;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtnum;
    // End of variables declaration//GEN-END:variables
}
